version: '3.3'

services:
  mariadb:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - db.env

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    ports:
      - "80:80"
    env_file:
      - wordpress.env
    volumes:
      - ./code:/code
      - ./var/html:/var/www/html

volumes:
  db_data:
